version: '3.6'

services:
  nginx:
    build:
      context: ..
      dockerfile: devops/image/nginx/Dockerfile
    ports:
      - "8000:80"
    networks:
      - default

networks:
  default:
    name: custom_game
    driver: bridge
