version: '3.6'

services:
  php-cli:
    volumes:
      - type: bind
        source: ..
        target: /var/www/app
#        consistency: delegated
      - type: bind
        source: ../../packages
        target: /var/www/packages
#        consistency: delegated
      - ../devops/image/php/dev.ini:/usr/local/etc/php/conf.d/xdebug_dev.ini