apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: APP_NAME-php-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: APP_NAME-php
    spec:
      containers:
        - name: APP_NAME-php
          image: gcr.io/GCLOUD_PROJECT_ID/APP_NAME-php:CI_COMMIT_SHA