apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        - name: master
          image: gcr.io/GCLOUD_PROJECT_ID/webapp-nginx:CI_COMMIT_SHA