# https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
providers:
  in_memory: { memory: ~ }
firewalls:
  dev:
    pattern: ^/(_(profiler|wdt)|css|images|js)/
    security: false
  main:
    stateless: true
    anonymous: true
    guard:
      authenticators:
        - SnakeTn\JwtSecurityBundle\Security\IamAuthenticator
