old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  #    producers:
  #        # use 'old_sound_rabbit_mq.task_producer' service to send data.
  #        task:
  #            connection:       default
  #            exchange_options: { name: 'task', type: direct }
  consumers:
    create_user:
      connection:       default
      exchange_options: { name: 'player', type: direct }
      queue_options:    { name: 'create_user'}
      callback:         App\Consumer\PlayerCreatedConsumer
