version: '3.6'

services:
  php-fpm:
    build:
      context: ..
      dockerfile: devops/image/php-fpm/Dockerfile
    networks:
      - default

  php-cli:
    build:
      context: ..
      dockerfile: devops/image/php-cli/Dockerfile
    networks:
      - default

  api-iam_nginx:
    build:
      context: ..
      dockerfile: devops/image/nginx/Dockerfile
    ports:
      - "8001:80"
    networks:
      - default
      - battleship

  mariadb:
    build:
      context: ..
      dockerfile: devops/image/mariadb/Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - default

  redis:
    build:
      context: ..
      dockerfile: devops/image/redis/Dockerfile
    networks:
      - default



networks:
  battleship:
    name: custom_battleship
    driver: bridge
  default:
    name: custom_ima
    driver: bridge
