version: '3.6'

services:
  php-fpm:
    volumes:
      - type: bind
        source: ..
        target: /var/www/app
        consistency: delegated
      - type: bind
        source: ../../packages
        target: /var/www/packages
        consistency: delegated
      - ../devops/image/php-fpm/dev.ini:/usr/local/etc/php/conf.d/xdebug_dev.ini

  php-cli:
    volumes:
      - type: bind
        source: ..
        target: /var/www/app
        consistency: delegated
      - type: bind
        source: ../../packages
        target: /var/www/packages
        consistency: delegated
      - ../devops/image/php-cli/dev.ini:/usr/local/etc/php/conf.d/xdebug_dev.ini
      - ../devops/image/php-cli/consumers.conf:/etc/supervisor/conf.d/consumers.conf

  mariadb:
    ports:
      - "3306:3306"