apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      containers:
        - name: master
          image: gcr.io/GCLOUD_PROJECT_ID/gameserver-php:CI_COMMIT_SHA